spring:
  data:
    mongodb:
      database: Ticket
      uri: mongodb://localhost

rabbitmq:
  addresses: localhost:5672
  exchange: eventExchange
  queueName: events
  routingkey: "path"

eventStore:
  mongodb:
    database: ${EVENT_STORE_DATABASE:eventStore}
    collection: ${EVENT_STORE_COLLECTION:events}
#axoniq:
#  axonserver:
#    event:
#      storage=: /events
#
axon:
  amqp:
    exchange: eventExchange
#  axonserver:
#    servers: "${AXON_SERVER:localhost}"
#  eventhandling:
#    processors:
#      name:
#        mode: tracking

server:
  port: 8081

abi.toggle.countries: ${TOGGLE_COUNTRY:BR,T1,T2,T3,T4,T5}