server:
    port: 8080

rabbitmq:
    exchange: topic
    queueName: events
    routingkey: "path"

spring:
    rabbitmq:
        addresses: localhost:5672
    logging:
        level:
            com.ambev.eventsource.relay: INFO



axon:
    amqp:
        exchange: topic